### ISSUE TITLE
Avoid using <u> and <b> tags for styling

### ISSUE THREAD

**Issue by NickDJM** [Restomak/portfolio#4]
You should avoid using `<u>` and `<b>` for style reasons. 

You can use the `text-decoration`([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)) property for underlines. This will allow you to have more control as well if you want to increase the thickness or something.

```css
// style.css
a {
  text-decoration: underline;
}
```
https://github.com/Restomak/portfolio/blob/ede7026f515f27f454ce687b2f205c1d5d57704d/index.html#L27

You can also use the [Bootstrap utility for text decoration](https://getbootstrap.com/docs/5.1/utilities/text/#text-decoration).

___

Instead of using `<b>` you can use `font-weight`([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight)).

```css
// style.css
h1 {
  font-weight: bold;
}
```

https://github.com/Restomak/portfolio/blob/ede7026f515f27f454ce687b2f205c1d5d57704d/index.html#L63

You can also use the [Bootstrap utility for font weights](https://getbootstrap.com/docs/5.1/utilities/text/#font-weight-and-italics).
